# Generated by Django 2.0.2 on 2018-02-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('network', models.CharField(max_length=50)),
                ('small_art', models.CharField(max_length=250)),
                ('large_art', models.CharField(max_length=250)),
                ('rss_feed_link', models.CharField(max_length=250)),
            ],
        ),
    ]
