# Generated by Django 2.0.2 on 2018-03-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20180307_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(max_length=450),
        ),
    ]
