# Generated by Django 2.0.2 on 2018-02-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20180222_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='release_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
